/**
 * Property-based tests for screenshot storage service
 * Feature: vibgyorseek-employee-monitoring
 * 
 * Property 14: Screenshot Storage Round-Trip
 * For any screenshot stored by the Dashboard_Server, the stored file should be retrievable 
 * using the returned file path, and the file metadata should include the correct employee 
 * identifier and timestamp.
 * 
 * Property 18: Screenshot Metadata Tracking
 * For any screenshot stored by the Dashboard_Server, the database record should contain 
 * a creation timestamp that matches the screenshot's captured_at time.
 * 
 * Validates: Requirements 9.4, 12.2
 */

import * as fc from 'fast-check';
import { ScreenshotService } from '../screenshot.service';
import { database } from '../../utils/database';
import { config } from '../../config';
import fs from 'fs';
import path from 'path';

// Mock dependencies
jest.mock('../../utils/database');
jest.mock('../../utils/logger', () => ({
  logger: {
    info: jest.fn(),
    debug: jest.fn(),
    warn: jest.fn(),
    error: jest.fn(),
  },
}));

describe('Screenshot Storage Service - Property-Based Tests', () => {
  let service: ScreenshotService;
  const testStoragePath = path.join(__dirname, 'test-screenshots-properties');
  let mockQuery: jest.Mock;

  beforeEach(() => {
    service = new ScreenshotService();
    mockQuery = database.query as jest.Mock;
    mockQuery.mockClear();
    
    // Override config for testing
    (config as any).screenshotStoragePath = testStoragePath;
    (config as any).screenshotTtlDays = 30;
  });

  afterEach(async () => {
    // Clean up test files
    try {
      if (fs.existsSync(testStoragePath)) {
        fs.rmSync(testStoragePath, { recursive: true, force: true });
      }
    } catch (error) {
      // Ignore cleanup errors
    }
  });

  describe('Property 14: Screenshot Storage Round-Trip', () => {
    /**
     * **Validates: Requirements 9.4**
     * 
     * Property: For any screenshot stored by the Dashboard_Server, the stored file should be 
     * retrievable using the returned file path, and the file metadata should include the 
     * correct employee identifier and timestamp.
     */
    it('should store and retrieve screenshot with correct metadata for any valid input', async () => {
      await fc.assert(
        fc.asyncProperty(
          // Generate valid screenshot storage inputs
          fc.record({
            employeeId: fc.uuid(),
            activityLogId: fc.uuid(),
            employeeName: fc.string({ minLength: 1, maxLength: 50 })
              .filter(s => s.trim().length > 0)
              .map(s => s.replace(/[/\\:*?"<>|]/g, '_')), // Remove invalid filename chars
            capturedAt: fc.date({ min: new Date('2024-01-01'), max: new Date('2025-12-31') }),
            screenshotData: fc.uint8Array({ minLength: 100, maxLength: 1000 })
              .map(arr => Buffer.from(arr).toString('base64')),
          }),
          async (data) => {
            const mockScreenshotId = fc.sample(fc.uuid(), 1)[0];
            
            // Mock database insert - capture the file path from the service
            mockQuery.mockImplementation((_query: string, params: any[]) => {
              return Promise.resolve({
                rows: [{
                  id: mockScreenshotId,
                  employee_id: data.employeeId,
                  activity_log_id: data.activityLogId,
                  file_path: params[2], // Use the file path generated by the service
                  file_size: Buffer.from(data.screenshotData, 'base64').length,
                  captured_at: data.capturedAt,
                  created_at: new Date(),
                  expires_at: new Date(data.capturedAt.getTime() + 30 * 24 * 60 * 60 * 1000),
                }],
              });
            });

            // Store the screenshot
            const storedScreenshot = await service.storeScreenshot(
              data.employeeId,
              data.activityLogId,
              data.screenshotData,
              data.capturedAt,
              data.employeeName.trim()
            );

            // Verify file was created and is retrievable
            expect(fs.existsSync(storedScreenshot.file_path)).toBe(true);
            
            // Read the file and verify content matches
            const fileContent = fs.readFileSync(storedScreenshot.file_path);
            const expectedContent = Buffer.from(data.screenshotData, 'base64');
            expect(fileContent.equals(expectedContent)).toBe(true);

            // Verify metadata includes correct employee identifier
            expect(storedScreenshot.employee_id).toBe(data.employeeId);
            
            // Verify metadata includes correct timestamp
            expect(storedScreenshot.captured_at.toISOString()).toBe(data.capturedAt.toISOString());
            
            // Verify file path contains employee name
            expect(storedScreenshot.file_path).toContain(data.employeeName.trim());
          }
        ),
        { numRuns: 100 }
      );
    }, 120000); // 120 second timeout for file operations

    /**
     * Property: For any screenshot with special characters in employee name,
     * the file should still be stored and retrievable
     */
    it('should handle special characters in employee names during storage', async () => {
      await fc.assert(
        fc.asyncProperty(
          fc.record({
            employeeId: fc.uuid(),
            activityLogId: fc.uuid(),
            employeeName: fc.string({ minLength: 1, maxLength: 30 })
              .filter(s => s.trim().length > 0)
              .map(s => s.replace(/[/\\:*?"<>|]/g, '_')),
            capturedAt: fc.date({ min: new Date('2024-01-01'), max: new Date('2025-12-31') }),
            screenshotData: fc.constant(Buffer.from('test-image').toString('base64')),
          }),
          async (data) => {
            const mockScreenshotId = fc.sample(fc.uuid(), 1)[0];
            
            mockQuery.mockImplementation((_query: string, params: any[]) => {
              return Promise.resolve({
                rows: [{
                  id: mockScreenshotId,
                  employee_id: data.employeeId,
                  activity_log_id: data.activityLogId,
                  file_path: params[2], // Use the file path generated by the service
                  file_size: Buffer.from(data.screenshotData, 'base64').length,
                  captured_at: data.capturedAt,
                  created_at: new Date(),
                  expires_at: new Date(data.capturedAt.getTime() + 30 * 24 * 60 * 60 * 1000),
                }],
              });
            });

            const storedScreenshot = await service.storeScreenshot(
              data.employeeId,
              data.activityLogId,
              data.screenshotData,
              data.capturedAt,
              data.employeeName.trim()
            );

            // Verify file exists and is readable
            expect(fs.existsSync(storedScreenshot.file_path)).toBe(true);
            const fileContent = fs.readFileSync(storedScreenshot.file_path);
            expect(fileContent.length).toBeGreaterThan(0);
          }
        ),
        { numRuns: 100 }
      );
    }, 120000);

    /**
     * Property: For any screenshot with varying data sizes,
     * the metadata should record the correct file size
     */
    it('should record correct file size in metadata for any screenshot data', async () => {
      await fc.assert(
        fc.asyncProperty(
          fc.record({
            employeeId: fc.uuid(),
            activityLogId: fc.uuid(),
            employeeName: fc.constant('TestEmployee'),
            capturedAt: fc.date({ min: new Date('2024-01-01'), max: new Date('2025-12-31') }),
            screenshotData: fc.uint8Array({ minLength: 50, maxLength: 5000 })
              .map(arr => Buffer.from(arr).toString('base64')),
          }),
          async (data) => {
            const expectedSize = Buffer.from(data.screenshotData, 'base64').length;
            const mockScreenshotId = fc.sample(fc.uuid(), 1)[0];
            
            mockQuery.mockImplementation((_query: string, params: any[]) => {
              return Promise.resolve({
                rows: [{
                  id: mockScreenshotId,
                  employee_id: data.employeeId,
                  activity_log_id: data.activityLogId,
                  file_path: params[2], // Use the file path generated by the service
                  file_size: expectedSize,
                  captured_at: data.capturedAt,
                  created_at: new Date(),
                  expires_at: new Date(data.capturedAt.getTime() + 30 * 24 * 60 * 60 * 1000),
                }],
              });
            });

            const storedScreenshot = await service.storeScreenshot(
              data.employeeId,
              data.activityLogId,
              data.screenshotData,
              data.capturedAt,
              data.employeeName
            );

            // Verify metadata records correct file size
            expect(storedScreenshot.file_size).toBe(expectedSize);
            
            // Verify file was created
            expect(fs.existsSync(storedScreenshot.file_path)).toBe(true);
          }
        ),
        { numRuns: 100 }
      );
    }, 120000);
  });

  describe('Property 18: Screenshot Metadata Tracking', () => {
    /**
     * **Validates: Requirements 12.2**
     * 
     * Property: For any screenshot stored by the Dashboard_Server, the database record 
     * should contain a creation timestamp that matches the screenshot's captured_at time.
     */
    it('should track creation timestamp matching captured_at for any screenshot', async () => {
      await fc.assert(
        fc.asyncProperty(
          fc.record({
            employeeId: fc.uuid(),
            activityLogId: fc.uuid(),
            employeeName: fc.string({ minLength: 1, maxLength: 50 })
              .filter(s => s.trim().length > 0)
              .map(s => s.replace(/[/\\:*?"<>|]/g, '_')),
            capturedAt: fc.date({ min: new Date('2024-01-01'), max: new Date('2025-12-31') }),
            screenshotData: fc.constant(Buffer.from('test-screenshot-data').toString('base64')),
          }),
          async (data) => {
            const mockScreenshotId = fc.sample(fc.uuid(), 1)[0];
            const createdAt = new Date();
            
            // Capture the parameters passed to database.query
            let capturedParams: any[] = [];
            mockQuery.mockImplementation((_query: string, params: any[]) => {
              capturedParams = params;
              return Promise.resolve({
                rows: [{
                  id: mockScreenshotId,
                  employee_id: params[0],
                  activity_log_id: params[1],
                  file_path: params[2],
                  file_size: params[3],
                  captured_at: params[4],
                  created_at: createdAt,
                  expires_at: params[5],
                }],
              });
            });

            const storedScreenshot = await service.storeScreenshot(
              data.employeeId,
              data.activityLogId,
              data.screenshotData,
              data.capturedAt,
              data.employeeName.trim()
            );

            // Verify database was called with correct captured_at
            expect(capturedParams[4]).toEqual(data.capturedAt);
            
            // Verify the returned screenshot has captured_at matching the input
            expect(storedScreenshot.captured_at.toISOString()).toBe(data.capturedAt.toISOString());
            
            // Verify created_at is set (should be close to current time)
            expect(storedScreenshot.created_at).toBeDefined();
            expect(storedScreenshot.created_at).toBeInstanceOf(Date);
          }
        ),
        { numRuns: 100 }
      );
    }, 120000);

    /**
     * Property: For any screenshot, the database record should include all required metadata fields
     */
    it('should include all required metadata fields for any screenshot', async () => {
      await fc.assert(
        fc.asyncProperty(
          fc.record({
            employeeId: fc.uuid(),
            activityLogId: fc.uuid(),
            employeeName: fc.string({ minLength: 1, maxLength: 50 })
              .filter(s => s.trim().length > 0)
              .map(s => s.replace(/[/\\:*?"<>|]/g, '_')),
            capturedAt: fc.date({ min: new Date('2024-01-01'), max: new Date('2025-12-31') }),
            screenshotData: fc.uint8Array({ minLength: 100, maxLength: 500 })
              .map(arr => Buffer.from(arr).toString('base64')),
          }),
          async (data) => {
            const mockScreenshotId = fc.sample(fc.uuid(), 1)[0];
            
            mockQuery.mockImplementation((_query: string, params: any[]) => {
              return Promise.resolve({
                rows: [{
                  id: mockScreenshotId,
                  employee_id: data.employeeId,
                  activity_log_id: data.activityLogId,
                  file_path: params[2], // Use the file path generated by the service
                  file_size: Buffer.from(data.screenshotData, 'base64').length,
                  captured_at: data.capturedAt,
                  created_at: new Date(),
                  expires_at: new Date(data.capturedAt.getTime() + 30 * 24 * 60 * 60 * 1000),
                }],
              });
            });

            const storedScreenshot = await service.storeScreenshot(
              data.employeeId,
              data.activityLogId,
              data.screenshotData,
              data.capturedAt,
              data.employeeName.trim()
            );

            // Verify all required metadata fields are present
            expect(storedScreenshot.id).toBeDefined();
            expect(storedScreenshot.employee_id).toBe(data.employeeId);
            expect(storedScreenshot.activity_log_id).toBe(data.activityLogId);
            expect(storedScreenshot.file_path).toBeDefined();
            expect(storedScreenshot.file_size).toBeGreaterThan(0);
            expect(storedScreenshot.captured_at).toBeInstanceOf(Date);
            expect(storedScreenshot.created_at).toBeInstanceOf(Date);
            expect(storedScreenshot.expires_at).toBeInstanceOf(Date);
          }
        ),
        { numRuns: 100 }
      );
    }, 120000);

    /**
     * Property: For any screenshot, the expires_at timestamp should be TTL days after captured_at
     */
    it('should calculate expires_at as TTL days after captured_at for any screenshot', async () => {
      await fc.assert(
        fc.asyncProperty(
          fc.record({
            employeeId: fc.uuid(),
            activityLogId: fc.uuid(),
            employeeName: fc.constant('TestEmployee'),
            capturedAt: fc.date({ min: new Date('2024-01-01'), max: new Date('2025-06-01') }),
            screenshotData: fc.constant(Buffer.from('test-data').toString('base64')),
          }),
          async (data) => {
            const mockScreenshotId = fc.sample(fc.uuid(), 1)[0];
            
            // Capture the expires_at parameter
            let capturedExpiresAt: Date | null = null;
            mockQuery.mockImplementation((_query: string, params: any[]) => {
              capturedExpiresAt = params[5]; // expires_at is the 6th parameter
              return Promise.resolve({
                rows: [{
                  id: mockScreenshotId,
                  employee_id: params[0],
                  activity_log_id: params[1],
                  file_path: params[2],
                  file_size: params[3],
                  captured_at: params[4],
                  created_at: new Date(),
                  expires_at: params[5],
                }],
              });
            });

            await service.storeScreenshot(
              data.employeeId,
              data.activityLogId,
              data.screenshotData,
              data.capturedAt,
              data.employeeName
            );

            // Verify expires_at is exactly TTL days after captured_at
            expect(capturedExpiresAt).not.toBeNull();
            const expectedExpiration = new Date(data.capturedAt);
            expectedExpiration.setDate(expectedExpiration.getDate() + config.screenshotTtlDays);
            expect(capturedExpiresAt!.getTime()).toBe(expectedExpiration.getTime());
          }
        ),
        { numRuns: 100 }
      );
    }, 120000);
  });
});
